"""Modifies users table

Revision ID: 264c1bddf19f
Revises: 081f5033dba1
Create Date: 2025-04-14 14:44:48.332207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264c1bddf19f'
down_revision = '081f5033dba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('endDate',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('endDate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
